apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: nginx-ingress
  name: nginx-ingress-prometheus
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
    targetPort: 10254
  selector:
    app: ingress-nginx
  sessionAffinity: None
  type: ClusterIP
