apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  clusterName: ""
  labels:
    app: prometheus
  name: nginx-ingress-prometheus
  namespace: ""
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - kube-system
    - monitoring
  selector:
    matchLabels:
      app: nginx-ingress
